const groups = [
  { slug: "niles-neighbors", name: "Niles Neighbors", district: "Niles", members: 214, meets: "first Wednesdays", description: "The historic district along Niles Boulevard, from the canyon mouth to the Alameda Creek trail.", topics: ["Historic district", "Niles Blvd traffic", "Alameda Creek trail", "Short-term rentals"], item: { ref: "PLN2026-00188", deadline: "Sep 13", label: "Written comments due", title: "Demolition of a 1912 bungalow on Second Street", body: "The owner wants to replace a contributing building in the Niles historic overlay with two townhomes; the board can require the street facade be kept.", topic: "Historic district", score: 94 }, outcome: { result: "Approved with changes", vote: "6–1", title: "Time limits for Niles Town Plaza parking", note: "Council kept the two-hour limit members asked for and dropped the proposed weekend meters." } },
  { slug: "irvington-commons", name: "Irvington Commons", district: "Irvington", members: 167, meets: "second Tuesdays", description: "Five Corners and the blocks around the planned Irvington BART station.", topics: ["Irvington BART", "Housing near transit", "Street safety", "Tree canopy"], item: { ref: "PLN2026-00176", deadline: "Sep 22", label: "Comment letters due", title: "Six-story apartments at Fremont and Washington Boulevards", body: "212 homes over ground-floor shops at Five Corners; staff recommends approval with 11 affordable units and reduced parking.", topic: "Housing near transit", score: 91 }, outcome: { result: "Approved", vote: "7–0", title: "Five Corners mural and plaza lighting", note: "Four members spoke at the hearing; the lighting was added after their comments." } },
  { slug: "mission-san-jose", name: "Mission San Jose Residents", district: "Mission San Jose", members: 298, meets: "third Thursdays, online", description: "Around the Mission, Ohlone College and the foothills along Mission Boulevard.", topics: ["Hillside development", "Mission Blvd safety", "Schools", "Wildfire readiness"], item: { ref: "PLN2026-00159", deadline: "Sep 21", label: "Comment letters due", title: "Hillside home above Mission Boulevard removing 18 oaks", body: "A 6,800 sq ft house on a 30% slope; the Hillside Initiative requires findings that it is not prominently visible from Mission Blvd.", topic: "Hillside development", score: 89 }, outcome: { result: "Denied", vote: "2–4", title: "Cell tower on church property off Mission Boulevard", note: "Commissioners agreed the tower failed the hillside visibility finding the group’s letter pointed to." } },
  { slug: "centerville-together", name: "Centerville Together", district: "Centerville", members: 131, meets: "last Saturdays", description: "Fremont Boulevard’s old town center, the Centerville train depot and the streets around them.", topics: ["Complete streets", "Housing", "Parks", "Noise"], item: { ref: "CC-26-0922-7A", deadline: "Sep 22", label: "eComments close", title: "Fremont Boulevard lane changes through Centerville", body: "Final design removes a travel lane each way through old Centerville to add protected bike lanes and wider sidewalks.", topic: "Complete streets", score: 90 }, outcome: { result: "Approved", vote: "5–2", title: "Safe overnight parking program at Centerville church lots", note: "Members were split, so the group published both letters instead of taking a side." } },
  { slug: "warm-springs-hillside", name: "Warm Springs Hillside Neighbors", district: "Warm Springs", members: 88, meets: "as needed, online", description: "The residential hillside neighborhood of Warm Springs, east of Mission Boulevard.", topics: ["Hillside initiative", "Wildfire readiness", "Water", "Traffic"], item: { ref: "PLN2026-00064", deadline: "Oct 02", label: "Comments due", title: "Replacement water tank on the Warm Springs hillside", body: "A replacement tank and access improvements are proposed above the neighborhood, with wildfire access and visual screening under review.", topic: "Wildfire readiness", score: 79 }, outcome: { result: "Approved", vote: "7–0", title: "Replacement water tank on the Warm Springs hillside", note: "The group supported the emergency-water reliability improvements." } }
];

const app = document.querySelector("#app");
const esc = (value) => String(value).replace(/[&<>"]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" })[c]);
const groupFor = (slug) => groups.find((group) => group.slug === slug) || groups[0];
const pagePath = () => location.hash.slice(1) || "/";
const link = (path, label, className = "") => `<a href="#${path}" class="${className}">${label}</a>`;

function mark() { return `<span class="mark" aria-hidden="true"><i></i><i></i><i></i></span>`; }
function header(active = "") {
  return `<header class="site-header"><div class="page nav"><a href="#/" class="brand">${mark()}<span>Docket</span></a><nav aria-label="Main"><a href="#/groups" class="${active === "groups" ? "active" : ""}">Groups</a><a href="#/places" class="${active === "places" ? "active" : ""}">Places</a><a href="#/" class="find-nav">Find your group</a></nav></div></header>`;
}
function footer() { return `<footer class="site-footer"><div class="page footer-inner"><p>${mark()}<strong>Docket</strong><span>· Fremont city hall, read for your neighborhood</span></p><p>Groups, agenda items and votes marked sample are demo data until the reading agent goes live.</p></div></footer>`; }
function itemCard(g) { const i = g.item; return `<article class="item-card"><div class="date-block"><span>Sat</span><strong>${i.deadline.split(" ")[1]}</strong><small>${i.deadline.split(" ")[0]} · ${i.label}</small></div><div class="item-body"><div class="item-meta"><code>${i.ref}</code><b>${i.topic}</b><span class="score">${i.score}/100 relevance</span></div><h3>${i.title}</h3><p>${i.body}</p><div class="item-footer"><strong>${i.label}</strong><span>Planning Commission · sample agenda</span></div></div></article>`; }
function home() {
  return `${header()}<main id="main"><section class="home-hero"><div class="page hero-content"><p class="intro">Docket reads every Fremont city-hall agenda and tells your neighborhood group what touches your streets, while there is still time to speak up.</p><form id="find-form" class="find-form"><h1><label for="address">Where do you live?</label></h1><div><input id="address" name="address" required autocomplete="street-address" placeholder="37600 Niles Blvd, Fremont" /><button>Find my group</button></div><p>A Fremont street address or the nearest cross street.</p></form><div class="stats"><p>Docket read <strong>4,380 pages</strong> of city documents this week and surfaced <strong>9 things</strong> across <strong>4 neighborhoods</strong>.</p><a href="#/groups">See the groups</a><span>Sample data</span></div></div><div class="hills" aria-hidden="true"><i></i><i></i><i></i><i></i></div></section><section class="page how"><p class="eyebrow">How Docket works</p><h2>City hall is easier to follow together.</h2><div class="feature-grid"><article><b>01</b><h3>Read the records</h3><p>The agent reads agendas, staff reports and decisions as they appear.</p></article><article><b>02</b><h3>Match the place</h3><p>Each item is connected to the neighborhoods and topics it may affect.</p></article><article><b>03</b><h3>Surface the choice</h3><p>Groups see the context, tradeoffs and deadline before the meeting.</p></article></div></section></main>${footer()}`;
}
function groupsPage() {
  return `${header("groups")}<main id="main"><section class="directory-head"><div class="page"><p class="eyebrow">Directory</p><h1>Neighborhood groups in Fremont</h1><p>${groups.length} groups, most recently active first. Each one hears about the city-hall items that touch its streets.</p></div></section><section class="page directory"><ul>${groups.map((g) => `<li><div><h2>${link(`/g/${g.slug}`, esc(g.name))}</h2><p>${g.description}</p><small><strong>${g.members}</strong> members · ${g.district} · Active this week</small></div><div class="urgent"><b>Most urgent</b><p>${g.item.title}</p><small>${g.item.label} · ${g.item.deadline}</small></div></li>`).join("")}</ul><p class="directory-note">Don’t see your block? <a href="#/">Look up your address</a>.</p></section></main>${footer()}`;
}
function groupPage(group) {
  return `${header("groups")}<main id="main"><section class="group-hero"><div class="page group-split"><div><p class="eyebrow">Fremont · ${group.district}</p><h1>${group.name}</h1><p class="description">${group.description}</p><dl><div><dt>Members</dt><dd>${group.members}</dd></div><div><dt>Watching</dt><dd>1</dd></div><div><dt>Meets</dt><dd>${esc(group.meets)}</dd></div></dl><a class="button" href="#/g/${group.slug}/join">Join ${group.name}</a></div><div class="map"><span>Sample neighborhood boundary</span><svg viewBox="0 0 440 280" role="img" aria-label="Illustrative map of ${group.name}"><path d="M0 32 90 0l79 59 95-27 176 47v201H0Z" fill="#e7f0f5"/><path d="M-14 190 92 130l64 28 88-85 231 77" fill="none" stroke="#aabec9" stroke-width="11"/><path d="M64 71 202 248 351 33" fill="none" stroke="#fff" stroke-width="12"/><path d="M56 53 218 65l104 85-92 81-120-32Z" fill="#8dc2f5" fill-opacity=".65" stroke="#262626" stroke-width="3"/><circle cx="192" cy="145" r="10" fill="#b3261e" stroke="white" stroke-width="4"/></svg></div></div></section><section class="page content-section"><p class="eyebrow">At Fremont city hall</p><h2>What we’re watching</h2>${itemCard(group)}</section><section class="outcomes"><div class="page"><p class="eyebrow">Decided</p><h2>Recent outcomes</h2><article class="outcome"><div><b class="approved">${group.outcome.result}</b><h3>${group.outcome.title}</h3><p>${group.outcome.note}</p></div><div class="vote"><strong>${group.outcome.vote}</strong><span>council vote</span><small>Group position: Supported</small></div></article></div></section><section class="page join-call"><h2>Join ${group.name}</h2><p>Free, and no password. See what’s coming up while there is still time to write a letter or show up.</p><a class="button" href="#/g/${group.slug}/join">Join the group</a></section></main>${footer()}`;
}
function joinPage(group) {
  return `${header("groups")}<main id="main" class="join-page"><section class="page"><a class="back" href="#/g/${group.slug}">← Back to ${group.name}</a><div class="join-card"><p class="eyebrow">${group.district} · ${group.members} members</p><h1>Join ${group.name}</h1><p>One screen, no password. You’ll see what the group is watching as soon as you join.</p><form id="join-form"><label>Your name<input required name="name" autocomplete="name"></label><label>Email<input required type="email" name="email" autocomplete="email"></label><fieldset><legend>Topics you care about</legend><p>Pick any. These are what ${group.name} watches.</p><div class="chips">${group.topics.map((topic) => `<label><input type="checkbox" value="${esc(topic)}"><span>${topic}</span></label>`).join("")}</div></fieldset><label class="check"><input type="checkbox"><span>I can sometimes speak at evening hearings</span></label><button>Join ${group.name}</button><p class="demo-note">Static Pages demo: this form does not send email or save personal data.</p></form></div></section></main>${footer()}`;
}
function placesPage() { return `${header("places")}<main id="main"><section class="directory-head"><div class="page"><p class="eyebrow">Places</p><h1>Follow the places that matter to your block</h1><p>Place matching is available in the full Docket app. This static demo includes the neighborhood groups and their sample agenda items.</p><a class="button" href="#/groups">Browse groups</a></div></section></main>${footer()}`; }
function resultPage(query) { const q = query.toLowerCase(); const group = groups.find((g) => q.includes(g.district.toLowerCase().split(" ")[0])) || groups[0]; return `${header()}<main id="main"><section class="page result"><p class="eyebrow">Sample address match</p><h1>You’re inside ${group.name}.</h1><p class="description">For the live app, Docket checks a Fremont address against neighborhood boundaries. This static demonstration selected a sample group.</p><article class="match-card"><div><p><strong>${esc(query)}</strong></p><h2>${group.name}</h2><p>${group.description}</p><a class="button" href="#/g/${group.slug}">See the group</a></div><div class="quick-item"><b>Watching right now</b><p>${group.item.title}</p><small>${group.item.label} · ${group.item.deadline}</small></div></article></section></main>${footer()}`; }
function render() {
  const path = pagePath();
  const join = path.match(/^\/g\/([^/]+)\/join$/);
  const group = path.match(/^\/g\/([^/]+)$/);
  if (path === "/groups") app.innerHTML = groupsPage();
  else if (path === "/places") app.innerHTML = placesPage();
  else if (join) app.innerHTML = joinPage(groupFor(join[1]));
  else if (group) app.innerHTML = groupPage(groupFor(group[1]));
  else if (path.startsWith("/find/")) app.innerHTML = resultPage(decodeURIComponent(path.slice(6)));
  else app.innerHTML = home();
  document.title = path === "/" ? "Docket — Fremont, California" : "Docket — static demo";
  bindForms(); window.scrollTo(0, 0);
}
function bindForms() {
  document.querySelector("#find-form")?.addEventListener("submit", (event) => { event.preventDefault(); const value = document.querySelector("#address").value.trim(); if (value) location.hash = `/find/${encodeURIComponent(value)}`; });
  document.querySelector("#join-form")?.addEventListener("submit", (event) => { event.preventDefault(); const form = event.currentTarget; const name = new FormData(form).get("name"); form.outerHTML = `<div class="joined"><p class="eyebrow">You’re in</p><h2>Thanks, ${esc(name)}.</h2><p>This static demo shows the local join experience. In the deployed application, Docket sends a secure sign-in link and saves your preferences.</p><a class="button" href="#/groups">Explore groups</a></div>`; });
}
window.addEventListener("hashchange", render); render();
