version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - github-actions
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: /backend
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - backend
    groups:
      python-dependencies:
        patterns:
          - "*"

  - package-ecosystem: npm
    directory: /frontend
    schedule:
      interval: weekly
      day: monday
    labels:
      - dependencies
      - frontend
    groups:
      javascript-dependencies:
        patterns:
          - "*"
