import type { Palette } from "@/components/pixel/Sprite";

// The Docket "D Lens" mark as 32×32 pixel art (one pixel per 8 units of the 256px vector).
// The D is the public record; the lens is the agent making it legible.
// app/icon.svg is the same grid; update both together.

export const LOGO_PALETTE: Palette = {
  B: "#102d3e", // ground
  N: "#102d3e", // lines of text under the lens
  W: "#edf1f3", // the D
  S: "#5a9fc4", // spine
  L: "#f8f6ef", // lens rim
  I: "#75bddc", // glass
  G: "#b9e2f2", // glint
  H: "#f2bc5b", // handle
  h: "#d49a3a", // handle shade
};

export const LOGO_ROWS = [
  "....BBBBBBBBBBBBBBBBBBBBBBBB....",
  "..BBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
  ".BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.",
  ".BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.",
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
  "BBBBBBBBSSSSSSWWWWBBBBBBBBBBBBBB",
  "BBBBBBBBSSSSSSWWWWWWWBBBBBBBBBBB",
  "BBBBBBBBSSSSSSWWWWWWWWBBBBBBBBBB",
  "BBBBBBBBSSSSSSWWWWWWWWWBBBBBBBBB",
  "BBBBBBBBSSSSSSWWWWWWWWWWBBBBBBBB",
  "BBBBBBBBSSSSSSBBLLLLWWWWBBBBBBBB",
  "BBBBBBBBSSSSSSLLGIIILLWWWBBBBBBB",
  "BBBBBBBBSSSSSLLGIIIIILLWWBBBBBBB",
  "BBBBBBBBSSSSSLINNNNNIILWWBBBBBBB",
  "BBBBBBBBSSSSSLIIIIIIIILWWBBBBBBB",
  "BBBBBBBBSSSSSLIIIIIIIILWWBBBBBBB",
  "BBBBBBBBSSSSSLINNNNIIILWWBBBBBBB",
  "BBBBBBBBSSSSSLLIIIIIILLWWBBBBBBB",
  "BBBBBBBBSSSSSSLLIIIILHHWWBBBBBBB",
  "BBBBBBBBSSSSSSBBLLLLWHHhBBBBBBBB",
  "BBBBBBBBSSSSSSWWWWWWWWHHhBBBBBBB",
  "BBBBBBBBSSSSSSWWWWWWWWWHHhBBBBBB",
  "BBBBBBBBSSSSSSWWWWWWWWBBHhBBBBBB",
  "BBBBBBBBSSSSSSWWWWWWWBBBBBBBBBBB",
  "BBBBBBBBSSSSSSWWWWBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
  "BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB",
  ".BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.",
  ".BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB.",
  "..BBBBBBBBBBBBBBBBBBBBBBBBBBBB..",
  "....BBBBBBBBBBBBBBBBBBBBBBBB....",
] as const;
